### Create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "virendra",
  "address": "e-403 roshan milestone",
  "email": "abcd@gmail.com",
  "dateOfBirth": "1998-08-13",
  "registeredDate": "2025-08-23"
}

###